image : microsoft/dotnet:latest

stages:
  - build
  - test

before_script:
  - 'dotnet --version'
  - 'dotnet migrate'
  - 'dotnet restore'

build:
 stage: build
 script:
  - 'dotnet build'

test:
 stage: test
 script:
  - 'echo Test FuWeb'
  - 'dotnet test src/Fu.Web/Fu.Web.csproj'

 only:
   - master